CREATE TABLE employees (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    salary DOUBLE NOT NULL,
    department VARCHAR(255) NOT NULL,
    contact_number VARCHAR(255) NOT NULL
);